#!/bin/bash
echo "Enter your choice\n1) instll zabbix 2.0\n2) install zabbix 3.0"
read options
echo $options
if [ $options = 1 ] 
then 
	sudo rpm -ivh http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
lif [ $options = 2 ]
then
	sudo rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
else
	echo Invalid Options
fi

exit 0

